#!/bin/sh

set -e

WORKDIR=$AUTOPKGTEST_TMP

if [ -n "${DEB_HOST_GNU_TYPE:-}" ]; then
    CROSS_COMPILE="$DEB_HOST_GNU_TYPE-"
else
    CROSS_COMPILE=
fi

${CROSS_COMPILE}gcc test/memory.c -o $WORKDIR/memory  \
	$(${CROSS_COMPILE}pkg-config --cflags atspi-2) \
	$(${CROSS_COMPILE}pkg-config --libs atspi-2) \
	$(${CROSS_COMPILE}pkg-config --cflags gobject-2.0) \
	$(${CROSS_COMPILE}pkg-config --libs gobject-2.0)

exec xvfb-run -s -noreset -a dbus-run-session --dbus-daemon debian/tests/dbus-daemon -- $WORKDIR/memory
