#!/bin/sh

set -e

WORKDIR=$(mktemp -d)
gcc test/memory.c -o $WORKDIR/memory  \
	$(pkg-config --cflags atspi-2) $(pkg-config --libs atspi-2) \
	$(pkg-config --cflags gobject-2.0) $(pkg-config --libs gobject-2.0)

exec xvfb-run dbus-run-session --dbus-daemon debian/tests/dbus-daemon -- /bin/sh -c "/usr/lib/at-spi2-core/at-spi-bus-launcher & /usr/lib/at-spi2-core/at-spi2-registryd 2> /dev/null & sleep 1 ; $WORKDIR/memory"
