/* Generated by wayland-scanner 1.23.0 */

/*
 * foo bar
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif


static const struct wl_interface *cosmic_atspi_v1_types[] = {
	NULL,
	NULL,
	NULL,
};

static const struct wl_message cosmic_atspi_manager_v1_requests[] = {
	{ "destroy", "", cosmic_atspi_v1_types + 0 },
	{ "add_key_grab", "uau", cosmic_atspi_v1_types + 0 },
	{ "remove_key_grab", "uau", cosmic_atspi_v1_types + 0 },
	{ "grab_keyboard", "", cosmic_atspi_v1_types + 0 },
	{ "ungrab_keyboard", "", cosmic_atspi_v1_types + 0 },
};

static const struct wl_message cosmic_atspi_manager_v1_events[] = {
	{ "key_events_eis", "h", cosmic_atspi_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface cosmic_atspi_manager_v1_interface = {
	"cosmic_atspi_manager_v1", 1,
	5, cosmic_atspi_manager_v1_requests,
	1, cosmic_atspi_manager_v1_events,
};

